services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ./postgres_data:/var/lib/postgresql
    environment:
      - 'POSTGRES_DB=usuarios'
      - 'POSTGRES_PASSWORD=a1b2c3d4'
      - 'POSTGRES_USER=devdb'
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U devdb -d usuarios" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432'
    networks:
      - red-backend-app

  usuarios-service:
    image: joseloaiza01/usuarios-bd-1.0:latest
    container_name: usuarios-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/usuarios
      - SPRING_DATASOURCE_USERNAME=devdb
      - SPRING_DATASOURCE_PASSWORD=a1b2c3d4
      - JPA_DDL=update
    networks:
      - red-backend-app

networks:
  red-backend-app:
    driver: bridge