app:
  api:
    version: v1
  version: 1.0.0

server:
  port: ${PORT:8080}
  address: 0.0.0.0

jwt:
  secret: ${JWT_SECRET:Secret_Key_Para_Local}
  expiration: 86400000 # 1 día
  refresh-expiration: 604800000 # 7 días
  refresh-secret: ${JWT_REFRESH_SECRET:default_refresh_secret}

openrouter:
  api-key: ${OPENROUTER_API_KEY:}
  model: openai/gpt-oss-120b:free

spring:
  application:
    name: usuarios-service
  jackson:
    time-zone: America/Bogota
    locale: es_CO
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      # Tiempo máximo que espera por una conexión del pool (30 seg)
      connection-timeout: 30000
      # Tiempo que espera para fallar si la DB no está disponible al arrancar
      # Un valor de -1 o uno alto ayuda a que no se cierre la app de inmediato
      initialization-fail-timeout: 60000
      # Pruebas de vida de la conexión
      keepalive-time: 30000
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL:update}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    defer-datasource-initialization: false
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
    show-sql: true

  sql:
    init:
      mode: never

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      co.uceva.usuariosservice: DEBUG

  main:
    allow-circular-references: true