app:
  api:
    version: v1
  version: 1.0.0

spring:
  application:
    name: usuarios-service
  jackson:
    time-zone: America/Bogota
    locale: es_CO
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    # 1. Cambia 'create-drop' por 'update' para que los datos no se borren al apagar
    hibernate:
      ddl-auto: ${JPA_DDL:update}
    defer-datasource-initialization: false
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true # Lo activamos para ver si los inserts funcionan

  # 3. FORZAR la ejecución del script SQL siempre
  sql:
    init:
      mode: never
      # data-locations: classpath:import.sql

  main:
    allow-circular-references: true